### ISSUE TITLE
GeoPlot - Java paths

### ISSUE THREAD

**Issue by foxm1** [antarctica/GeoPlot#33]

**Comment by Ulvetanna** [comment]
This is a bit more work. But given the geoJSON output of Marias codebase we should be able to plot GeoPlot.Paths. This currently isn't working as the Paths are very restrictive on the data passed. Think there needs to be a flag that allows DataFrames or geoJSON not in the same form as PolarRoute

**Comment by Ulvetanna** [comment]
I have assigned this issue to @Ulvetanna to get this update made in the next couple of days.

**Comment by SamuelHall700** [comment]
@Ulvetanna - Can this be moved to the GeoPlot issues, or closed if the task has been complete?

**Comment by gecoombs** [comment]
Closing as stale, feel free to reopen if needed :slightly_smiling_face:

**Comment by SamuelHall700** [comment]
Cheers George, I think this one can stay closed :)
