### ISSUE TITLE
Very minor README.md bug for install of Geoplot

### ISSUE THREAD

**Issue by matscorse** [antarctica/GeoPlot#58]
Capitalisation in path incorrect in README.md

```
pip install -e ./GeoPlot
```
should be
```
pip install -e ./Geoplot
```

**Comment by SamuelHall700** [comment]
Cheers for this, Mat; I've put a quick change into main to update the README.

**Comment by gecoombs** [comment]
I've changed this again to match the use of camel case for GeoPlot elsewhere in the repo. The real issue here was that a different format was used in the `git clone` and `pip install` commands.
