### ISSUE TITLE
PyPi - GeoPlot

### ISSUE THREAD

**Issue by Ulvetanna** [antarctica/GeoPlot#8]
This issue will address getting GeoPlot up on pypi for an open code release.

- [x] Familiarise how to deploy on `pypi`
- [x] Check if `GeoPlot` name is taken
- [x] Push package

In order to complete this task, other issues must also be completed.

**Comment by Ulvetanna** [comment]
@JimCircadian I check to see if `geoplot` was taken for, of which it is. What's a standard form that I should follow to determine a similar name, e.g. is `geo-plot` ok ? or should I change the software to `geo_plot` ? :)

**Comment by JimCircadian** [comment]
The module will need to be geo_plot (you can't do `import geo-plot` for example) so I prefer the second one, but you can call the package geo-plot, it always just feels a bit weird to me. Ironically geo_plot seems to need to be geo-plot in the filesystem, so it's all a bit weird.

**Comment by Ulvetanna** [comment]
Okie dokie. Is it worth sticking with `geo_plot` even if the filesystem does `geo-plot`. Or is it worth coming up with a new name entirely, promise this is the last question ?

**Comment by JimCircadian** [comment]
Yeah I think `geo_plot` will be best :)

**Comment by Ulvetanna** [comment]
Package name was changed to `bas-geoplot` and all repo was updated

**Comment by Ulvetanna** [comment]
There is an issue with the inclusion of the dependencies. Need to run

>python setup.py sdist bdist_wheel
>twine upload dist/*
